# This workflow will run any files matching "tests/*_test.py" using the Python
# unittest module.

name: Run Python unit tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./requirements.txt

      - name: Run all tests
        if: github.repository == 'leonhard-s/auraxium'
        env:
          SERVICE_ID: ${{secrets.REPO_SERVICE_ID}}
        run: |
          python -m unittest discover -p *_test.py tests/

      - name: Run only offline tests
        if: github.repository != 'leonhard-s/auraxium'
        run: |
          python -m unittest discover -p *_test.py tests/
